### PR TITLE
fix: allowing RS256 without alg

### LINKED ISSUE #16: Cannot get to work with Microsoft Entra
The keys array returned from Microsoft Entra do not include an "alg" attribute, thus causing the following line of code to fail to retrieve the key, despite their being a matching "kid", there is no "alg"

https://github.com/nearform/fastify-jwt-jwks/blob/2800d59e430affbf3605587a1427f90eb3dd07f9/index.js#L115

Microsoft Entra keys retrieved from here: https://login.microsoftonline.com/common/discovery/v2.0/keys

Microsoft Documentation here: https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#validate-the-signature

### PR DESCRIPTION
**Pull request by marceloFerreira90**
closes #16

main change line: 
` k => k.kid === kid && ((k.alg && k.alg === alg) || (k.kty && k.kty === 'RSA' && k.use === 'sig'`

Updated tests

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -157,7 +159,7 @@ function fastifyJwtJwks(instance, options, done) {
       request[decodeFunctionName]({ decode: { complete: true } })
         .then(decoded => {
           const { header } = decoded
-
+          console.log(decoded.header)
```
Comment (simoneb) [inline index.js:162]: remove

**Review by simoneb — APPROVED** [review]
